---
title: "Economic Output and Risk Factors"
author: "Nathan Seto"
output: pdf_document
---

```{r, include = FALSE}
library(knitr)
library(tidyr)
library(tidyverse)
library(readr)
library(data.table)
library(dplyr)
opts_chunk$set(echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE, tidy = TRUE)
output_risk_combined <- readr::read_csv("~/internship/workspace/Analysis/output_risk_combined.csv")
```

## What is the relationship between health risk concentrations and economic output?

#### Calculate correlations between environmental exposures and farm sales (and/or other econ. variables) to understand economic linkages.

```{r, include = FALSE}
source("C:/Users/natha/OneDrive/Documents/internship/workspace/Analysis/outputriskfunction.R")
process_risk_data(output_risk_combined, "crop_totals_sales_measured_in_$")
correlation_df <- correlation_df[-1,]
split_dfs <- split(correlation_df, correlation_df$category)
list2env(split(correlation_df, correlation_df$category), envir = .GlobalEnv)
```

#### Correlation Coefficients between predictor $X$ and `Crop Total Sales ($)`

```{r}
tibble(income[,-4])
```

```{r}
tibble(salesQuantity[,-4])
```

```{r}
tibble(crops[,-4])
```

```{r}
tibble(animals[,-4])
```

```{r}
tibble(agriculturalLand[,-4])
```

```{r}
tibble(area_operated[,-4])
```

```{r}
tibble(nature[,-4])
```

```{r}
tibble(costs[,-4])
```

```{r}
tibble(expectedLoss[,-4])
```

```{r}
tibble(operations[,-4])
```

```{r}
tibble(riskIndex[,-4])
```

```{r}
tibble(social[,-4])
```

```{r}
tibble(other[,-4])
```
